spring:
  datasource:
    url: jdbc:h2:mem:kairos
    driver-class-name: org.h2.Driver
    username: kairos
    password: kairos
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: 'classpath:data-default.sql'
      mode: always
logging:
  level:
    org:
      hibernate:
        type: trace